"""add attendance_records

Revision ID: cdd70f7b870c
Revises: bc51246dcb92
Create Date: 2026-10-04 17:01:36.701885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdd70f7b870c'
down_revision: Union[str, Sequence[str], None] = 'bc51246dcb92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance_records',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('clock_in_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('clock_out_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('clock_out_time IS NULL OR clock_out_time > clock_in_time', name='attendance_out_after_in'),
    sa.ForeignKeyConstraint(['tenant_id', 'user_id'], ['memberships.tenant_id', 'memberships.user_id'], name='attendance_membership_fk'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('attendance_one_open_uq', 'attendance_records', ['tenant_id', 'user_id'], unique=True, postgresql_where=sa.text('clock_out_time IS NULL AND deleted_at IS NULL'))
    op.create_index('attendance_tenant_user_in_idx', 'attendance_records', ['tenant_id', 'user_id', 'clock_in_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('attendance_tenant_user_in_idx', table_name='attendance_records')
    op.drop_index('attendance_one_open_uq', table_name='attendance_records', postgresql_where=sa.text('clock_out_time IS NULL AND deleted_at IS NULL'))
    op.drop_table('attendance_records')
    # ### end Alembic commands ###
